<a href="https://colab.research.google.com/github/Qagent/Qagent/blob/main/Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 

chars = {0: '|', 1: 'ँ', 2: 'ं', 3: 'ः', 4: 'अ', 5: 'आ', 6: 'इ', 7: 'ई', 8: 'उ', 9: 'ऊ', 10: 'ऋ', 11: 'ए', 12: 'ऐ', 13: 'ऑ', 14: 'ओ', 15: 'औ', 16: 'क', 17: 'ख', 18: 'ग', 19: 'घ', 20: 'ङ', 21: 'च', 22: 'छ', 23: 'ज', 24: 'झ', 25: 'ञ', 26: 'ट', 27: 'ठ', 28: 'ड', 29: 'ढ', 30: 'ण', 31: 'त', 32: 'थ', 33: 'द', 34: 'ध', 35: 'न', 36: 'प', 37: 'फ', 38: 'ब', 39: 'भ', 40: 'म', 41: 'य', 42: 'र', 43: 'ल', 44: 'व', 45: 'श', 46: 'ष', 47: 'स', 48: 'ह', 49: '़', 50: 'ा', 51: 'ि', 52: 'ी', 53: 'ु', 54: 'ू', 55: 'ृ', 56: 'ॅ', 57: 'े', 58: 'ै', 59: 'ॉ', 60: 'ो', 61: 'ौ', 62: '्'}


In [ ]:
df=pd.read_csv('/content/drive/My Drive/hi.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import torch
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self, annotations_file, data, shuffle=None, scramble=None):
        self.labels = annotations_file
        self.data = data

    def __len__(self):
        return int(self.data.size/2)

    def __getitem__(self, idx):
        return self.data.iloc[idx,1]

HindiCSV  =  CustomDataset(chars, df)
H = {}
for i in range(len(HindiCSV)):
  try:
    lit = HindiCSV[i].split(" ")
  except:
    print(i)

  for j in lit:
    if j in H: H[j] += 1
    else: H[j] = 1


6150
7889
8217
8271
8274
8383
8391
8403
8410
8412
8415
8416
8420
8422
8432
8448
8463
8559
8584
8626
8644
8662
8676
8684
8731
8781
9673
10119
10585
14878
15338
39402
48995
49809
57116
60296
62379
63833
63834
63840
63843
63873
63887
63894
63896
63901
66646
67045
67063
67092
67121
67225
67366
67866
67870
67872
67880
67982
67987
67989
67995
67999
68000
68117
68126
68133
68141
68205
68206
68210
68214
68239
68263
68301
68377
68475
68594
68624
68661
68682
68718
68724
68731
68766
68775
68793
68882
68919
69105
69151
69323
70127
70262
72237
72908
77108
77830
84238
84248
84312
85649
85795
91228
91406
91671
91672
91722
92029
92471
92477
92481
92482
92485
92486
92490
92491
92493
92495
92553
92560
92616
92639
92644
92649
92650
92655
92681
92688
92700
92708
92721
92771
92780
92805
92819
92849
92872
92936
92937
92969
92990
93042
93045
93057
93063
93086
93125
93132
93159
93172
93201
93204
93240
93260
93284
93295
93298
93317
93337
93342
93403
93504
93512
93523
93562
93563
93581
93630
93720
93739
93749
9

In [ ]:
len(H)
maxi = -1
for i in H:
  if maxi < len(i):
    maxi = len(i)
print(maxi)
H

304


{'मुस्कुराहट': 28868,
 'हम': 928699,
 'सारे': 167229,
 'गमों': 473,
 'कोभूल': 13,
 'जाते': 355364,
 'क्योंकि': 271657,
 'हंसी': 40736,
 'हमें': 258845,
 'भुलाने': 1146,
 'माध्यम': 6580,
 '': 47709783,
 'क्या': 1942541,
 'कहना': 91441,
 'आसान': 24128,
 'हंसना': 2353,
 'साधारण': 12143,
 'सी': 319356,
 'क्रिया': 7268,
 'किंतु': 21248,
 'चेहरे': 245475,
 'लाना': 12354,
 'कठिन': 10226,
 'कार्य': 26147,
 'मेरी': 762711,
 'बुआजी': 3438,
 'बेटी': 179028,
 'उसने': 1063072,
 'जन्म': 45729,
 'लिया': 575745,
 'जीवन': 125945,
 'खुशियों': 13338,
 'नजारा': 8875,
 'कभी': 564538,
 'दिखाया': 14981,
 'दुखी': 30148,
 'हमेशा': 171852,
 'मुस्कुरा': 130867,
 'हर': 305310,
 'बात': 1599770,
 'उत्तर': 28274,
 'देती': 198827,
 'मैं': 2154035,
 'आशा': 28277,
 'आने': 297156,
 'भविष्य': 22744,
 'होगा': 412556,
 'सही': 220786,
 'मायने': 8392,
 'लेकर': 375476,
 'आएगा': 38928,
 'इतनी': 275745,
 'उदास': 54444,
 'चुपचाप': 77384,
 'रहती': 125805,
 'बीमारी': 15648,
 'परेशान': 185979,
 'चिंता': 85112,
 'साल': 177660,
 'उम्

In [ ]:
from torch import nn
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.vlen = 12
        self.maxlen = 30
        self.w1 = torch.randn(self.vlen, self.vlen, requires_grad=True)
        self.w2 = torch.randn(self.vlen, self.vlen, requires_grad=True)
        self.w3 = torch.randn(self.vlen, self.vlen, requires_grad=True)
        
        self.K, self.V, self.Q = torch.zeros(size=(3, self.vlen, self.maxlen)) # [  13 characters  ]

        self.seqBlock = nn.Sequential(
            nn.Linear(1, 12),
            nn.Sigmoid(),
        )

    def forward(self, x):
        b = torch.randn(12, requires_grad=True)
        z = self.seqBlock(x) + b

        k = torch.matmul(self.w2, z) 
        q = torch.matmul(self.w1, z)   
        v = torch.matmul(self.w3, z)

        sm = nn.Softmax(dim=1);
        temp = torch.matmul(self.Q, torch.t(self.K))
        temp2 = torch.matmul(sm(temp), self.V)
        print(temp2.shape, temp2)
        
        #TODO: ATTN
        
        #DEC

        


        return q, k, v

device = 'cuda' if torch.cuda.is_available() else 'cpu'  
model = NeuralNetwork().to(device)
print(model)
model = NeuralNetwork()
model.forward(torch.rand(1))

NeuralNetwork(
  (seqBlock): Sequential(
    (0): Linear(in_features=1, out_features=12, bias=True)
    (1): Sigmoid()
  )
)
torch.Size([12, 15]) tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


(tensor([ 3.5487,  3.6804, -1.9426,  8.2732, -1.3793,  1.0749, -5.1206,  2.0036,
         -6.4034,  6.3486,  4.2909,  0.3808], grad_fn=<MvBackward0>),
 tensor([-3.1332, -8.4235,  0.6575, -2.4996, -1.9058, -0.0355, -0.6935,  6.8203,
         -7.3331, -3.6604, -0.8917, -4.9773], grad_fn=<MvBackward0>),
 tensor([ -4.4072,   6.2317,   8.7320,  -7.7033,   3.2025,   6.8651,   1.6487,
          -2.9217,   4.9882,  -9.9503,   1.6974, -11.0899],
        grad_fn=<MvBackward0>))

In [ ]:
maxi = -1
for i in H:
  if maxi < len(i):
    maxi = len(i)
    print(i)
print(maxi)

मुस्कुराहट
परिस्थितियों
चतुर्वेदीप्रिय
एम्‍हर्स्‍टबर्ग
एमहर्स्‍टबर्गवाले
अद्वैतमच्युतनादिमनंतरुपमाद्यं
यद्रच्छालाभषसंतुष्टोद्वंद्वातीतो
भुशब्दपरमेश्वरकेलियेहैजोअसीमज्ञान
प्रभाशुभप्रचारणीमहाष्टसिद्धिकामिनी
️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️️
वल्लवीवल्लभायार्चितायात्मनेकंसविध्वंसिने
विद्युदुद्योतवत्प्रस्फुरद्वाससंप्रावृडम्भोदवत्प्रोल्लसद्विग्रहम्
राधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधेराधे
120


Flatten(
  start_dim=tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), end_dim=-1
)


TypeError: ignored

In [ ]:
D= 15
K,V,Q = torch.zeros(size=(3, 12, D))
print(K)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [ ]:
input_text = torch.rand(1)
print(input_text.size())

layer1 = nn.Linear(in_features=1, out_features=12)
hidden1 = layer1(input_text)
print(hidden1.size())

torch.Size([1])
torch.Size([12])


In [ ]:
model.forward(torch.rand(1))

tensor([0.2760])

In [ ]:
X = torch.rand(1, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

IndexError: ignored

In [ ]:
import torch

x = torch.rand(1)
y = torch.rand(1, 12)

w = torch.randn(1, 12, requires_grad=True)
b = torch.randn(1, requires_grad=True)
z = torch.matmul(x, w)+b

loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(loss)

ValueError: ignored